presubmits:
  - name: f5gc-operator-unit-test
    decorate: true
    run_if_changed: "^.*.go$"
    spec:
      containers:
      - image: nephio/gotests:1671656214984921088
        command:
        - "/bin/sh"
        args:
        - "-c"
        - |
          make unit

  - name: f5gc-operator-lint
    decorate: true
    run_if_changed: "^.*.go$"
    spec:
      containers:
      - image: nephio/gotests:1671656214984921088
        command:
        - "/bin/sh"
        args:
        - "-c"
        - |
          make lint

  - name: f5gc-operator-gosec
    decorate: true
    run_if_changed: "^.*.go$"
    spec:
      containers:
      - image: nephio/gotests:1671656214984921088
        command:
        - "/bin/sh"
        args:
        - "-c"
        - |
          make gosec

  - name: f5gc-operator-license-header-check
    decorate: true
    run_if_changed: "^.*.go$"
    spec:
      containers:
      - image: nephio/gotests:1671656214984921088
        command:
        - "/bin/sh"
        args:
        - "-c"
        - |
          "/usr/local/bin/checklicense.sh"
  - name: presubmit-f5gc-operator-lichen
    decorate: true
    run_if_changed: "^.*.go$"
    spec:
      containers:
      - image: nephio/gotests:1671656214984921088
        command:
        - "/usr/local/bin/lichen.sh"
