presubmits:
  - name: f5gc-operator-unit-test
    decorate: true
    run_if_changed: "^.*.go$"
    spec:
      containers:
      - image: nephio/gotests:7
        command:
        - "/bin/sh"
        args:
        - "-c"
        - |
          make unit

  - name: f5gc-operator-lint
    decorate: true
    run_if_changed: "^.*.go$"
    spec:
      containers:
      - image: nephio/gotests:7
        command:
        - "/bin/sh"
        args:
        - "-c"
        - |
          make lint

  - name: f5gc-operator-gosec
    decorate: true
    run_if_changed: "^.*.go$"
    spec:
      containers:
      - image: nephio/gotests:7
        command:
        - "/bin/sh"
        args:
        - "-c"
        - |
          make gosec

  - name: f5gc-operator-license-header-check
    decorate: true
    run_if_changed: "^.*.go$"
    spec:
      containers:
      - image: nephio/gotests:7
        command:
        - "/bin/sh"
        args:
        - "-c"
        - |
          "/usr/local/bin/checklicense.sh"
  - name: presubmit-f5gc-operator-lichen
    decorate: true
    always_run: true
    spec:
      containers:
      - image: nephio/gotests:7
        command:
        - "/bin/bash"
        args:
        - "-c"
        - |
          for i in \
          $(egrep -rl --null --include \*.go 'package\s+main\b' | xargs -0 -L 1  dirname  | sort -u | xargs -d '\n' -L 1 printf "%s " ) ; \
          do cd $i; echo $i; rm -f /tmp/cmd; go build -o "/tmp/cmd"; lichen -c /etc/lichen.yaml "/tmp/cmd" || exit 1; cd - ;done
