
# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  namespace: free5gc
  name: free5gc-operator-metrics-monitor
  labels:
    control-plane: free5gc-operator
    app.kubernetes.io/name: servicemonitor
    app.kubernetes.io/instance: free5gc-operator-metrics-monitor
    app.kubernetes.io/component: metrics
    app.kubernetes.io/created-by: nephio
    app.kubernetes.io/part-of: free5gc-operator
    app.kubernetes.io/managed-by: kustomize

spec:
  endpoints:
    - path: /metrics
      port: https
      scheme: https
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: true
  selector:
    matchLabels:
      control-plane: free5gc-operator
