apiVersion: v1
kind: Service

metadata:
  namespace: free5gc
  name: free5gc-operator-metrics-service
  labels:
    control-plane: free5gc-operator
    app.kubernetes.io/name: service
    app.kubernetes.io/instance: free5gc-operator-metrics-service
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: nephio
    app.kubernetes.io/part-of: free5gc-operator
    app.kubernetes.io/managed-by: kustomize

spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: free5gc-operator
