apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata:
  name: proxy-role
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: proxy-role
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: nephio
    app.kubernetes.io/part-of: free5gc-operator
    app.kubernetes.io/managed-by: kustomize

rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
