apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: leader-election-rolebinding
  labels:
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/instance: leader-election-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: nephio
    app.kubernetes.io/part-of: free5gc-operator
    app.kubernetes.io/managed-by: kustomize

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: leader-election-role
subjects:
- kind: ServiceAccount
  name: free5gc-operator
  namespace: free5gc
