//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InterfaceConfig) DeepCopyInto(out *InterfaceConfig) {
	*out = *in
	if in.IPs != nil {
		in, out := &in.IPs, &out.IPs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.GatewayIPs != nil {
		in, out := &in.GatewayIPs, &out.GatewayIPs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Vlan != nil {
		in, out := &in.Vlan, &out.Vlan
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InterfaceConfig.
func (in *InterfaceConfig) DeepCopy() *InterfaceConfig {
	if in == nil {
		return nil
	}
	out := new(InterfaceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *N6InterfaceConfig) DeepCopyInto(out *N6InterfaceConfig) {
	*out = *in
	in.Interface.DeepCopyInto(&out.Interface)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new N6InterfaceConfig.
func (in *N6InterfaceConfig) DeepCopy() *N6InterfaceConfig {
	if in == nil {
		return nil
	}
	out := new(N6InterfaceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NFCondition) DeepCopyInto(out *NFCondition) {
	*out = *in
	in.LastProbeTime.DeepCopyInto(&out.LastProbeTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NFCondition.
func (in *NFCondition) DeepCopy() *NFCondition {
	if in == nil {
		return nil
	}
	out := new(NFCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UPFCapacity) DeepCopyInto(out *UPFCapacity) {
	*out = *in
	out.UplinkThroughput = in.UplinkThroughput.DeepCopy()
	out.DownlinkThroughput = in.DownlinkThroughput.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UPFCapacity.
func (in *UPFCapacity) DeepCopy() *UPFCapacity {
	if in == nil {
		return nil
	}
	out := new(UPFCapacity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UPFDeployment) DeepCopyInto(out *UPFDeployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UPFDeployment.
func (in *UPFDeployment) DeepCopy() *UPFDeployment {
	if in == nil {
		return nil
	}
	out := new(UPFDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UPFDeployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UPFDeploymentList) DeepCopyInto(out *UPFDeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UPFDeployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UPFDeploymentList.
func (in *UPFDeploymentList) DeepCopy() *UPFDeploymentList {
	if in == nil {
		return nil
	}
	out := new(UPFDeploymentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UPFDeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UPFDeploymentSpec) DeepCopyInto(out *UPFDeploymentSpec) {
	*out = *in
	in.Capacity.DeepCopyInto(&out.Capacity)
	if in.N3Interfaces != nil {
		in, out := &in.N3Interfaces, &out.N3Interfaces
		*out = make([]InterfaceConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.N4Interfaces != nil {
		in, out := &in.N4Interfaces, &out.N4Interfaces
		*out = make([]InterfaceConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.N6Interfaces != nil {
		in, out := &in.N6Interfaces, &out.N6Interfaces
		*out = make([]N6InterfaceConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.N9Interfaces != nil {
		in, out := &in.N9Interfaces, &out.N9Interfaces
		*out = make([]InterfaceConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UPFDeploymentSpec.
func (in *UPFDeploymentSpec) DeepCopy() *UPFDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(UPFDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UPFDeploymentStatus) DeepCopyInto(out *UPFDeploymentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]NFCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UPFDeploymentStatus.
func (in *UPFDeploymentStatus) DeepCopy() *UPFDeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(UPFDeploymentStatus)
	in.DeepCopyInto(out)
	return out
}
