---
# Source: free5gc-amf/templates/amf-configmap.yaml
#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: amf-configmap
  labels:
    app: free5gc
data:
  amfcfg.yaml: |
    info:
      version: 1.0.3
      description: AMF initial local configuration

    configuration:
      serviceNameList:
        - namf-comm
        - namf-evts
        - namf-mt
        - namf-loc
        - namf-oam

      ngapIpList:
        - 10.100.50.249
      sbi:
        scheme: http
        registerIPv4: amf-namf # IP used to register to NRF
        bindingIPv4: 0.0.0.0  # IP used to bind the service
        port: 80
        tls:
          key: config/TLS/amf.key
          pem: config/TLS/amf.pem
      
      nrfUri: http://nrf-nnrf:8000
      amfName: AMF
      serviceNameList:
        - namf-comm
        - namf-evts
        - namf-mt
        - namf-loc
        - namf-oam
      servedGuamiList:
        - plmnId:
            mcc: 208
            mnc: 93
          amfId: cafe00
      supportTaiList:
        - plmnId:
            mcc: 208
            mnc: 93
          tac: 1
      plmnSupportList:
        - plmnId:
            mcc: 208
            mnc: 93
          snssaiList:
            - sst: 1
              sd: 010203
            - sst: 1
              sd: 112233
      supportDnnList:
        - internet
      security:
        integrityOrder:
          - NIA2
        cipheringOrder:
          - NEA0
      networkName:
        full: free5GC
        short: free      
      locality: area1 # Name of the location where a set of AMF, SMF and UPFs are located
      networkFeatureSupport5GS: # 5gs Network Feature Support IE, refer to TS 24.501
        enable: true # append this IE in Registration accept or not
        length: 1 # IE content length (uinteger, range: 1~3)
        imsVoPS: 0 # IMS voice over PS session indicator (uinteger, range: 0~1)
        emc: 0 # Emergency service support indicator for 3GPP access (uinteger, range: 0~3)
        emf: 0 # Emergency service fallback indicator for 3GPP access (uinteger, range: 0~3)
        iwkN26: 0 # Interworking without N26 interface indicator (uinteger, range: 0~1)
        mpsi: 0 # MPS indicator (uinteger, range: 0~1)
        emcN3: 0 # Emergency service support indicator for Non-3GPP access (uinteger, range: 0~1)
        mcsi: 0 # MCS indicator (uinteger, range: 0~1)
      t3502Value: 720
      t3512Value: 3600
      non3gppDeregistrationTimerValue: 3240
      # retransmission timer for paging message
      t3513:
        enable: true     # true or false
        expireTime: 6s   # default is 6 seconds
        maxRetryTimes: 4 # the max number of retransmission
      # retransmission timer for NAS Registration Accept message
      t3522:
        enable: true     # true or false
        expireTime: 6s   # default is 6 seconds
        maxRetryTimes: 4 # the max number of retransmission
      # retransmission timer for NAS Registration Accept message
      t3550:
        enable: true     # true or false
        expireTime: 6s   # default is 6 seconds
        maxRetryTimes: 4 # the max number of retransmission
      # retransmission timer for NAS Authentication Request/Security Mode Command message
      t3560:
        enable: true     # true or false
        expireTime: 6s   # default is 6 seconds
        maxRetryTimes: 4 # the max number of retransmission
      # retransmission timer for NAS Notification message
      t3565:
        enable: true     # true or false
        expireTime: 6s   # default is 6 seconds
        maxRetryTimes: 4 # the max number of retransmission
      t3570:
        enable: true     # true or false
        expireTime: 6s   # default is 6 seconds
        maxRetryTimes: 4 # the max number of retransmission

    logger:
      AMF:
        ReportCaller: false
        debugLevel: info
      Aper:
        ReportCaller: false
        debugLevel: info
      FSM:
        ReportCaller: false
        debugLevel: info
      NAS:
        ReportCaller: false
        debugLevel: info
      NGAP:
        ReportCaller: false
        debugLevel: info
---
# Source: free5gc-amf/templates/amf-service.yaml
#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
apiVersion: v1
kind: Service
metadata:
  name: amf-namf
  labels:
    helm.sh/chart: free5gc-amf-0.2.3
    app.kubernetes.io/name: free5gc-amf
    app.kubernetes.io/instance: amf
    app.kubernetes.io/version: "v3.2.0"
    app.kubernetes.io/managed-by: Helm
    project: free5gc
    nf: amf
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: free5gc-amf
    app.kubernetes.io/instance: amf
    project: free5gc
    nf: amf
---
# Source: free5gc-amf/templates/amf-deployment.yaml
#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: amf-free5gc-amf-amf
  labels:
    helm.sh/chart: free5gc-amf-0.2.3
    app.kubernetes.io/name: free5gc-amf
    app.kubernetes.io/instance: amf
    app.kubernetes.io/version: "v3.2.0"
    app.kubernetes.io/managed-by: Helm
    project: free5gc
    nf: amf
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: free5gc-amf
      app.kubernetes.io/instance: amf
      project: free5gc
      nf: amf
  template:
    metadata:
      annotations:
                
        k8s.v1.cni.cncf.io/networks: '[
            { "name": "n2network-amf",
              "interface": "n2",
              "ips": [ "10.100.50.249/29" ],
              "gateway": [ "10.100.50.254" ]
            }]'
        checksum/config: e55252b780f735a002080d1a8c9e9ca06bb0f1b0947e7249a6edff99fce5000a
      labels:
        app.kubernetes.io/name: free5gc-amf
        app.kubernetes.io/instance: amf
        project: free5gc
        nf: amf
    spec:
      imagePullSecrets:
        []
      securityContext:
        {}
      initContainers:
      - name: wait-nrf
        image: towards5gs/initcurl:1.0.0
        env:
        - name: DEPENDENCIES
          value: http://nrf-nnrf:8000
        command: ['sh', '-c', 'set -x; for dependency in $DEPENDENCIES; do while [ $(curl --insecure --connect-timeout 1 -s -o /dev/null -w "%{http_code}" $dependency) -ne 200 ]; do echo waiting for dependencies; sleep 1; done; done;']   
      
      containers:
      - name: amf
        image: towards5gs/free5gc-amf:v3.2.0
        imagePullPolicy: Always
        securityContext:
            {}
        ports:
        - containerPort: 80
        ports:
        - name: namf
          containerPort: 80
        - name: n2
          containerPort: 38412
          protocol: SCTP
        command: ["./amf"]
        args: ["-c", "../config/amfcfg.yaml"]
        env:
          - name: GIN_MODE
            value: release
        volumeMounts:
        - mountPath: /free5gc/config/
          name: amf-volume
        resources:
            limits:
              cpu: 150m
              memory: 128Mi
            requests:
              cpu: 150m
              memory: 128Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      nodeSelector:
        {}
      affinity:
        {}
      tolerations:
        []

      volumes:
      - name: amf-volume
        projected:
          sources:
          - configMap:
              name: amf-configmap
---
# Source: free5gc-amf/templates/amf-hpa.yaml
#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
---
# Source: free5gc-amf/templates/amf-ingress.yaml
#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
---
# Source: free5gc-amf/templates/amf-networkattachmentdefinition.yaml
#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: n2network-amf
spec:
  config: '{
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "macvlan",
          "capabilities": { "ips": true },
          "master": "eth0",
          "mode": "bridge",
          "ipam": {
            "type": "static",
            "routes": [
              {
                "dst": "0.0.0.0/0",
                "gw": "10.100.50.254"
              }
            ] 
          }
        }, {
          "capabilities": { "mac": true },
          "type": "tuning"
        }
      ]
    }'
---
# Source: free5gc-amf/templates/tests/test-connection.yaml
#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
apiVersion: v1
kind: Pod
metadata:
  name: "amf-free5gc-amf-test-connection"
  labels:
    helm.sh/chart: free5gc-amf-0.2.3
    app.kubernetes.io/name: free5gc-amf
    app.kubernetes.io/instance: amf
    app.kubernetes.io/version: "v3.2.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['amf-namf:80']
  restartPolicy: Never
