# permissions for end users to view amfdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: amfdeployment-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: free5gc-operator
    app.kubernetes.io/part-of: free5gc-operator
    app.kubernetes.io/managed-by: kustomize
  name: amfdeployment-viewer-role
rules:
- apiGroups:
  - workload.nephio.org
  resources:
  - amfdeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - workload.nephio.org
  resources:
  - amfdeployments/status
  verbs:
  - get
