# permissions for end users to view imageconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: imageconfig-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: free5gc-operator
    app.kubernetes.io/part-of: free5gc-operator
    app.kubernetes.io/managed-by: kustomize
  name: imageconfig-viewer-role
rules:
- apiGroups:
  - free5gc.nephio.org
  resources:
  - imageconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - free5gc.nephio.org
  resources:
  - imageconfigs/status
  verbs:
  - get
